#!/usr/bin/env bash
# Domain and subdomain information
domain="yourdomain.com"
subdomains=("www" "lb-01" "web-01" "web-02")

# Loop through subdomains and display information
for subdomain in "${subdomains[@]}"; do
    destination=$(dig +short "$subdomain.$domain" | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")

    echo "The subdomain $subdomain points to $destination"
done
